repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.1
        hooks:
        -   id: end-of-file-fixer
        -   id: check-ast
        -   id: check-yaml
        -   id: trailing-whitespace
        -   id: debug-statements
        -   id: check-merge-conflict
        -   id: check-json
        # -   id: pretty-format-json

    -   repo: https://github.com/psf/black
        rev: 21.8b0
        hooks:
        -   id: black

    -   repo: https://github.com/pre-commit/mirrors-eslint
        rev: 'v8.0.0-beta.1'
        hooks:
        -   id: eslint
