arch: amd64
os: linux
dist: focal # xenial and trusty fail to install PPA (see Dockerfile step-> add-apt-repository ppa:deadsnakes/ppa)
language: python

python:
  - "3.9"

services:
  - docker

git:
  depth: 50

env:
  global:
    - PROJECT_NAME: "turbocommerce"
    - secure: "kFh+fhVrUrpHShGNBGLcKSJlPrdFdIVk0WHLrp/RQL/qz/QmjFR06ng0kvdq8g+4oKxF5WutpZTOqNA3HseQdVTV00hcyYO+iINozLktUEAcVMNBDyAtH4nkfhUqdHwdAe8SftkDDsgEaTd3OrpZDgj8N038WH2iDpjMcWJ0+OWrB9dIRZG53wBIAxP8G0XVAkpJfaQEVBYv79GnfO8ReuA0dhAtm6ki3euosnFFBRATUA1+ccRvVIBWRWmhROVzN7QIxdeM80cBDQJSNRNM8BmDuiCYZvgw6y0yEDqvhqPnjAa0bzN/s0S0IRKGOpLXs7BUHXC62XOphLm/W6rW2vo5QE085ZCDebftI8p8qoWqgKs1vn5xa93qAFBthw/4D0TqYx07tMMyU+HaOeltRvMeBKYOimCdook6ODfyHPQYfIEaxpYLHpVpwoh9GFGknxtIt+jxBfs8DShdzrwn33pJxZiBQoYAKidCUGZt8PgDKO1tYYwLxelPrT1OX+XVk8TkGAoT7j35vUK5tcjcIKfuG/Qe7+N0CgUvlA+/ler2P4T9y2MyvJcNG/7YPTHZnIxAhlxLENzlfnBpXzBQHsRkQNAZxMQnRacL3jS2p7uSRqrdcWY6GVIpza2/2T7kIlG/3BE7ObjbaWOlPbGIVY7PT6W0VnKNeB6wbEP4W4U="
    - REACT_APP_URL: "https://localhost:3000"
    - DEBUG: 1
    - secure: "eCDvSz0ojNNoXF90gxTnwiiQ8nm8NZDPiUNIHrr9MJmC2renLo6sa7cpQMR3P+zgsxpXAUEf7ZwU+j971M6QqFN6UjK7ckuAqcv5gNW1GuvcMF2E2rK0KpxeIGKI+Ajo/S0IBHBv9tE4Rpv4qbR5BXF+9qKKjv88VP7Ec08QUutGLtt1RPenzL4dQ16L2pQKf9CjAsBlpKWeqgETa3mzYyj3UYbrwuI2E+S5iKPuMzEFYeE9lDZAZs+Q5e5tMuuo3B6zZgwqzhNg74zAe+b7H8q5Qda+Glwwr+sC/ntOOPpzt/GnpW+MNOklivdq0BLxppaIJ+lGu5Kd7iXC0Mn1U1Su1NFPEsVPtuTtxBWg0CMn4afAL4JqZdfS+gQkALSHAJtzh7zdpcpQzfnAOE+oOqjU4lBDXrn0Ce77Odj5eWUKg7zeeR5b6v2rcNV5jGTxypVtc+WAhfiWSk9Bsvjma3lqehR8kTHdyfXK0nPjkvBr7OsAgH5c6tCe1xkNPowstouizGhazps6l2yc/5iIJ+0J1Q4bnvrsddHYI7qjEO09uvCaNNsBBV0YVKRgOXDrmzEFhPd0vTCaicPcZLGfu1j7Cbc1uWxI68z5dHxPSB5nlR/6PdkGQLvb9CP99tzbg6rDLUdj9LGliczNpDV+9YQCYB+OsgwTu0GI2Icd1gk="
    - secure: "QvYlWDl+dJr8uvSHrSKZTJbOhPt1OaW6HsSHqUQM8dbu9i2i0NMn7ngQeyme0OZPCQLgp+guGyAEwI6tgtuODhXxTdNxJMLya1Ap0hLfK6V/BcOYghCQNzZdUmEHYT+YRFVjBxpDLQ9eN374w0JHlCwbrtv0HWVovbcvFNHqlDH1a5S0aKXthJLF8PvaCrtq9PQPAhXzVdLDvx3vAr0NNwLS8Ej21d6yJXaUZpxbO5FjAn050WkBG1XToaVZ4e8eJuxYtB7cbJnuQG+TAgAB1bK6Wnt/qBU3KWv/MTRaLkbueolfbXB17KXLWPZ3cn5rRLyvCHgQPCUYbL6PzXDkZmgMqanAkEUDcwH74cP8vHz/D/jtbZLOWjkdx1HzmdrSyNdEb0rKf5ro/NIyRSpWZMzz4q7Uzf9GZDH31Lyofkpc/XlHVSkcnEPMOODs2FzTzpJGRoPIuFy4z5dO0LON96J0Or0brR5hmXsaFZqMLfa5Cs6l5LlLZ/Knf3pr6kMoCRZTH5b53FjyRF9Pi1GUpTb0IFtc0s/JpYIYgJcP2qO6z53s5g0Dd4ERbM82T7LsopHSZH/PCDYYViKZ5kioXqn6HCbV3i9ladGv5DAW8yJyxHKneEPbiqE5pj+6drF3YPiqYwUUTR8RdOXSNZ9cE23KQTPfJI09aXk3edqSpX8="
    - secure: "YsKF/PCXDYwBloYgxtNiW3QtH9lc0UmLRcLAENQkdPYialeCKxPd8end+C2Pqu8hE0dC4ScXsTngwSixZNd2gYuTkxUtfbm55nmCzjYeZgM4n1cNTM1RhMNFM98ietGgtQrKfE315GEuTGHKxwiWBcfqcpAkoSzvxqm3fTeowLTaX6+GxBxd8Cv2EVw22k+u48PBrrB0W/YAnia/cETWSauuYylJqDxVDA6JPjqh+D6MV0IEBxtWOun3P9AL8ZaBWVsf8hrVrI9cnQawDC0uUkpharJk9svtAgoJmIc9jC6lbKMHVDZGDz74Vykmss/dbC7X/4JaB7ho4BgavbhhtdB+Cs7YaeEGIrWJ68VMocscu0jEywv3o3qHczG3DhnIakblfUBsnVkRRavA7zvU1Gq/LX69YWTpUmuGnRQR1tlb5AaCXrGzGAxhBEgA087QbcyAel+yUUgSiJIdCvABaWkFDn72EShROo/Mv5N9qo3wVB0k8baIitLYNGZ4c9L553uW2uv0L84OeqTqOCeBgHP2kw+q9lCysHGMt9Tg3SwHELt0ZppiY82FAGMu9tZzIRzbRn1h9kyq4/D2+lNs12Xq0612ldB4aM/nmcXTYs3KAQwzVzJuxfvtg3wPveZM8rWFp7okQsQecCdtE8W9IQTNsg4LH8cJux7zwG54x4Q="
    - REST_FRAMEWORK_PAGE_SIZE: 10
    - REST_FRAMEWORK_MAX_PAGE_SIZE: 1000
    - POSTGRES_NAME: postgres
    - POSTGRES_USER: postgres
    - POSTGRES_PASSWORD: root
    - POSTGRES_HOST: "turbocommerce_db"
    - POSTGRES_PORT: 5432

cache:
  - pip

before_install:
  - chmod +x $HOME
  - chown -R travis $HOME
  - bash ./travis/make_env_file.sh
  - docker-compose run -d turbocommerce_db
  - docker-compose build turbocommerce_backend

script:
  - docker run -it --rm --name turbocommerce_backend turbocommerce_backend bash -c "python3 manage.py test --no-input --keepdb "
