version: "3.3"

services:

  backend:
    build:
        context: .
        dockerfile: backend/Dockerfile
    command: python3 backend/src/manage.py runsslserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/backend
    stdin_open: true
    tty: true

  db:
    image: postgres
    expose:
      - "5432"
    env_file:
        - backend/.env
