version: "3.3"

services:

  turbocommerce_backend:
    image: turbocommerce_backend
    container_name: turbocommerce_backend
    build:
        context: ./backend
        dockerfile: ./Dockerfile
    command: >
      sh -c "chmod +x wait_for_it.sh
            ./wait_for_it.sh turbocommerce_db:5432
            python3 manage.py migrate
            python3 manage.py runsslserver 0.0.0.0:8000"
    depends_on:
      - turbocommerce_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/turbocommerce_backend/src
    stdin_open: true
    tty: true

  turbocommerce_db:
    image: postgres
    container_name: turbocommerce_db
    expose:
      - "5432"
    env_file:
        - backend/.env.local
    volumes:
      - ./postgres:/var/lib/postgresql/data
