version: "3.3"

services:

  turbocommerce_backend:
    image: turbocommerce_backend
    container_name: turbocommerce_backend
    build:
        context: ./backend
        dockerfile: ./Dockerfile
    command: >
      sh -c "chmod +x start_server.sh && ./start_server.sh"
    depends_on:
      - turbocommerce_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/turbocommerce_backend/src
    stdin_open: true
    tty: true

  turbocommerce_db:
    image: postgres
    container_name: turbocommerce_db
    expose:
      - "5432"
    env_file:
        - backend/.env.local
    volumes:
      - ./postgres:/var/lib/postgresql/data
