version: "3.8"
   
services:

  backend:
    build:
        context: .
        dockerfile: backend/Dockerfile
    command: python backend/src/manage.py runserver
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/backend

  db:
    image: postgres
    expose:
      - "5432"
    env_file:
        - backend/.env