version: "3.3"

services:

  turbocommerce_backend:
    image: turbocommerce_backend
    container_name: turbocommerce_backend
    build:
        context: .
        dockerfile: backend/Dockerfile
    command: ["python3", "backend/src/manage.py", "runsslserver", "0.0.0.0:8000"]
    depends_on:
      - turbocommerce_db
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/backend
    stdin_open: true
    tty: true

  turbocommerce_db:
    image: postgres
    container_name: turbocommerce_db
    expose:
      - "5432"
    env_file:
        - backend/.env.local
    volumes:
      - ./postgres:/var/lib/postgresql/data
