version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run python ./backend/src/manage.py test --keepdb
          name: TestTurbocommerceBackend

workflows:
  main:
    jobs:
      - build-and-test
