# Generated by Django 3.1.3 on 2021-05-09 20:36

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_description",
                    models.TextField(blank=True, max_length=3000, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=520, null=True, unique=True
                    ),
                ),
                ("returnable", models.BooleanField(default=False)),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "brand_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=520, null=True, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductGrandParentCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=520, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Grand Parent Categories",
            },
        ),
        migrations.CreateModel(
            name="ProductMeasurement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurement_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LENGTH", "LENGTH"),
                            ("WIDTH", "WIDTH"),
                            ("HEIGHT", "HEIGHT"),
                            ("WEIGHT", "WEIGHT"),
                            ("WAIST", "WAIST"),
                            ("BUST", "BUST"),
                            ("CHEST", "CHEST"),
                            ("RADIUS", "RADIUS"),
                            ("DIAMETER", "DIAMETER"),
                            ("VOLUME", "VOLUME"),
                            ("SHOULDER", "SHOULDER"),
                            ("COLLAR", "COLLAR"),
                            ("SLEEVE", "SLEEVE"),
                            ("CUFF", "CUFF"),
                            ("THICKNESS", "THICKNESS"),
                            ("INSEAM", "INSEAM"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("measurement_value", models.IntegerField(blank=True, null=True)),
                (
                    "measurement_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AMPERE", "AMPERE"),
                            ("CELCIUS", "CELCIUS"),
                            ("CENTIMETER", "CENTIMETER"),
                            ("GALLON", "GALLON"),
                            ("KELVIN", "KELVIN"),
                            ("METER", "METER"),
                            ("MILLIMETER", "MILLIMETER"),
                            ("LITRE", "LITRE"),
                            ("MILLILITRE", "MILLILITRE"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "measurement",
                    models.ManyToManyField(to="products.ProductMeasurement"),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("stock_keeping_unit", models.BigIntegerField(unique=True)),
                ("discount", models.IntegerField()),
                ("published", models.BooleanField(default=False)),
                ("price", models.IntegerField()),
                ("weight_in_grams", models.IntegerField()),
                (
                    "color",
                    colorfield.fields.ColorField(
                        blank=True, default=None, max_length=18, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variants",
                        related_query_name="product_variant",
                        to="products.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.productsize",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("warehouse_name", models.CharField(max_length=255)),
                (
                    "address_street_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_street_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("province", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductVariantSpecification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "specification_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "specification_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variant_specifications",
                        related_query_name="product_variant_specification",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductVariantInventory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("trace_quantity", models.BooleanField(default=True)),
                ("quantity", models.IntegerField()),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variant_inventories",
                        related_query_name="product_variant_inventory",
                        to="products.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_variant_warehouses",
                        related_query_name="product_variant_warehouse",
                        to="products.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product variant inventory",
            },
        ),
        migrations.CreateModel(
            name="ProductVariantImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=products.models.generate_upload_path_for_images
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variant_images",
                        related_query_name="product_variant_image",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductParentCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=520, null=True, unique=True
                    ),
                ),
                (
                    "grand_parent_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_parent_categories",
                        related_query_name="product_parent_category",
                        to="products.productgrandparentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parent Categories",
            },
        ),
        migrations.CreateModel(
            name="ProductChildCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=520, null=True, unique=True
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_child_categories",
                        related_query_name="product_child_category",
                        to="products.productparentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Child Categories",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.productbrand"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="child_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productchildcategory",
            ),
        ),
    ]
