# Generated by Django 3.1.3 on 2021-05-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productchildcategory",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=520, unique=True),
            preserve_default=False,
        ),
    ]
