# Generated by Django 3.1.3 on 2021-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20210516_2036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="stock_keeping_unit",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
