# Generated by Django 3.1.3 on 2020-11-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20201120_1648"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmeasurement",
            old_name="measurment_value",
            new_name="measurement_value",
        ),
    ]
