# Generated by Django 3.1.3 on 2020-11-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_auto_20201129_1021"),
    ]

    operations = [
        migrations.AddField(
            model_name="productspecification",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productspecification",
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
