# Generated by Django 3.1.3 on 2020-11-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productspecification_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmeasurement",
            name="measurement_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AMPERE", "AMPERE"),
                    ("CELCIUS", "CELCIUS"),
                    ("CENTIMETER", "CENTIMETER"),
                    ("GALLON", "GALLON"),
                    ("KELVIN", "KELVIN"),
                    ("METER", "METER"),
                    ("MILLIMETER", "MILLIMETER"),
                    ("LITRE", "LITRE"),
                    ("MILLILITRE", "MILLILITRE"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
