# Generated by Django 3.1.3 on 2020-11-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20201129_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_image",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_specification",
                to="products.product",
            ),
        ),
    ]
