# Generated by Django 3.1.7 on 2021-02-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20210222_0049"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariantinventory",
            name="assigned_warehouses",
        ),
        migrations.AddField(
            model_name="productvariantinventory",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_variant_warehouses",
                related_query_name="product_variant_warehouse",
                to="products.warehouse",
            ),
        ),
    ]
