# Generated by Django 3.1.7 on 2021-02-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_auto_20210223_0652"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="stock_keeping_unit",
            field=models.BigIntegerField(unique=True),
        ),
    ]
