# Generated by Django 3.1.7 on 2021-03-09 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_auto_20210223_0655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productchildcategory",
            name="parent_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_child_categories",
                related_query_name="product_child_category",
                to="products.productparentcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productparentcategory",
            name="grand_parent_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_parent_categories",
                related_query_name="product_parent_category",
                to="products.productgrandparentcategory",
            ),
        ),
    ]
