# Generated by Django 3.1.3 on 2021-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_remove_creditcard_edit_customershippingaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customershippingaddress",
            name="address_street_line_1",
        ),
        migrations.RemoveField(
            model_name="customershippingaddress",
            name="address_street_line_2",
        ),
        migrations.AddField(
            model_name="customershippingaddress",
            name="address",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="customershippingaddress",
            name="address_type",
            field=models.CharField(
                choices=[("HOME", "HOME"), ("OFFICE", "OFFICE")],
                default="HOME",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customershippingaddress",
            name="alternate_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customershippingaddress",
            name="country_code_alternate_phone_number",
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customershippingaddress",
            name="country_code_primary_phone_number",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customershippingaddress",
            name="customer_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customershippingaddress",
            name="default_address",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customershippingaddress",
            name="primary_phone_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
