# Generated by Django 3.1.7 on 2021-04-13 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20210327_0700"),
        ("customer", "0002_auto_20210411_1745"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerwishlist",
            name="products",
        ),
        migrations.AddField(
            model_name="customerwishlist",
            name="products",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
