# Generated by Django 3.1.3 on 2021-05-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeinformation",
            name="default_currency",
            field=models.CharField(default="₹", max_length=20),
            preserve_default=False,
        ),
    ]
