# Generated by Django 3.1.7 on 2021-03-23 22:56

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="store_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.path_for_store_logo
            ),
        ),
    ]
