# Generated by Django 3.1.7 on 2021-04-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20210417_1127"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoreCustomer",
        ),
    ]
