# Generated by Django 3.1.3 on 2021-05-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_storecustomer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="store_host_url",
        ),
        migrations.DeleteModel(
            name="StoreCustomer",
        ),
    ]
