# Generated by Django 3.1.3 on 2020-11-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address_pincode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
