# Generated by Django 3.1.7 on 2021-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customershippingaddress",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("CUSTOMER", "CUSTOMER"), ("ADMIN", "ADMIN")], max_length=20
            ),
        ),
        migrations.DeleteModel(
            name="CustomerCreditCard",
        ),
        migrations.DeleteModel(
            name="CustomerShippingAddress",
        ),
    ]
