# Generated by Django 3.1.3 on 2021-05-11 15:27

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.CustomUserManager()),
            ],
        ),
    ]
