# Generated by Django 3.1.7 on 2021-04-18 21:20

from django.db import migrations, models


def move_username_to_email(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        user.email = user.username
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210408_1451"),
    ]

    operations = [
        migrations.RunPython(move_username_to_email),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
