# Generated by Django 3.1.3 on 2021-06-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210511_1527"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address_pincode",
        ),
    ]
